version: '3.7'
services: 
    jenkins:
        build: .
        container_name: jenkins-container
        privileged: true
        user: root
        ports:
            - 8083:8080
            - 50003:50000
        networks:
            - jenkins
        volumes:
            - jenkins-vol:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock 
            - /usr/bin/docker:/usr/bin/docker
volumes: 
    jenkins-vol:   
networks:
    jenkins: